# Generated by Django 4.2.23 on 2025-08-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['name'], name='job_name_prefix_idx', opclasses=['varchar_pattern_ops']),
        ),
    ]
